# https://circleci.com/docs/2.0/

version: 2
workflows:
  version: 2
  ci:
    jobs:
      - "lint"
      - "debian-8"
      - "debian-9"

jobs:
  lint:
    docker:
      - image: "circleci/python:2"

    steps:
      - "checkout"

      - run:
          name: "Static-ish code checks"
          command: |
            pip install --user tox
            ~/.local/bin/tox -e codechecks

  debian-8:
    docker:
      - image: "debian:8"

    steps:
      - "checkout"

      - run:
          name: "Bootstrap test environment"
          command: |
            apt-get --quiet update
            apt-get --quiet --yes install \
                build-essential \
                python2.7 \
                python2.7-dev \
                libffi-dev \
                libssl-dev \
                libyaml-dev \
                virtualenv
            virtualenv --python python2.7 tests
            tests/bin/pip install tox

      - run:
          name: "Run test suite"
          command: |
            tests/bin/tox -e py27

  debian-9:
    docker:
      - image: "debian:9"

    steps:
      - "checkout"

      - run:
          name: "Bootstrap test environment"
          command: |
            apt-get --quiet update
            apt-get --quiet --yes install \
                build-essential \
                python2.7 \
                python2.7-dev \
                libffi-dev \
                libssl-dev \
                libyaml-dev \
                virtualenv
            virtualenv --python python2.7 tests
            tests/bin/pip install tox

      - run:
          name: "Run test suite"
          command: |
            tests/bin/tox -e py27
