name: Python package

on: [push]

jobs:
  build:

    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version:
          - "2.7"

    steps:
    # Get MS VC++ 9
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: "9"
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel tox
    - name: Get Tahoe-LAFS master
      run: |
        pip wheel --wheel-dir ./wheelhouse git+https://github.com/tahoe-lafs/tahoe-lafs@bdist-wheel-with-version#egg=tahoe-lafs
    - name: Test with tox
      run: |
        PIP_FIND_LINKS=./wheelhouse tox -e py27-coverage
